apiVersion: apps/v1
kind: Deployment
metadata:
  name: chocolat-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chocolat-app
  template:
    metadata:
      labels:
        app: chocolat-app
    spec:
      containers:
        - name: chocolat-container
          image: zeldris77/chocolat:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: chocolat-service
spec:
  selector:
    app: chocolat-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      # nodePort: 30001
  type: LoadBalancer
